worlds:
    - world
weather: true
nodrop: true
forcespawn: true
no-fall-damage: true
jumppads: true
magicclock: true
doublejump: true
void: true
notab: true
block-all-commands: true
blocked-cmd: true

JumpPadID: 70 # Stone Plate
BottomBlockId: 152 # Dirt
VelocityMultiplier: 3 
clockitemname: "&2Magic Clock" # ClockName
clockslot: 4 # What slot to be in? 0-xx
voidY: 25 # Y, when should we TP a player?

show-players-message: "&2Players are visible!"
hide-players-message: "&4Players are invisible!"

blocked-cmds:
    - op
no-perm-message: "&4You don't have permission!"
