main: com.macxgaming.hubmc.hubmc
version: 1.0
name: HubMC
depend: [ProtocolLib]
author: MacXGaming
commands:
    hsetspawn:
        usage: /<command>
        aliases: [sspawn]
        description: Set the spawn.
    hreload:
        usage: /<command>
        description: Reload config
permissions:
  hubmc.use:
    description: Use Double Jump, VOID, Magic Clock and NoDrop
    default: true
  hubmc.fs.no:
    description: No Force Spawn
    default: false    
  hubmc.admin:
    description: Get acces to /hsetspawn and /hreload
    default: false
  hubmc.mc.always:
    description: Get access to always visible
    default: false
  hubmc.block.override:
    description: Get access to all blocked commands
    default: false
  hubmc.inv.move:
    description: Get able to move items in inventory
    default: false
  hubmc..commandtab.bypass:
    description: Get able to TAB commands
    default: false