main: com.macxgaming.hubmc.hubmc
version: 1.0
name: HubMC
author: MacXGaming
commands:
    hsetspawn:
        usage: /<command>
        aliases: [sspawn]
        description: Set the spawn.
    hreload:
        usage: /<command>
        description: Reload config
permissions:
  hubmc.use:
    description: Use Double Jump, VOID, ForceSpawn, Magic Clock and NoDrop
    default: true
  hubmc.admin:
    description: Get acces to /hsetspawn and /hreload
    default: false
  hubmc.mc.always:
    description: Get acces always visible
    default: false    
  hubmc.block.override:
    description: Get acces to all blocked commands
    default: false      
  hubmc.inv.move:
    description: Get able to move items in inventory
    default: false          